export const DATABASE_CONNECT_TIMEOUT_SECONDS = 10;
export const DATABASE_IDLE_TIMEOUT_SECONDS = 20;
export const DATABASE_MAX_LIFETIME_SECONDS = 300;
export const DATABASE_STATEMENT_TIMEOUT_MS = 15_000;
